version: "v2.12.2"

networks:
  myapp:
    external: true

services:
  json:
    image: morozhka/json:v0.1.0
    container_name: json
    build:
      context: json-service
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    environment:
      - HTTP_PORT=3030
    networks:
      - myapp

  yaml:
    image: morozhka/yaml:v0.1.0
    container_name: yaml
    build:
      context: yaml-service
      dockerfile: Dockerfile
    ports:
      - 3031:3031
    environment:
      - HTTP_PORT=3031
    networks:
      - myapp

  gob:
    image: morozhka/gob:v0.1.0
    container_name: gob
    build:
      context: gob-service
      dockerfile: Dockerfile
    ports:
      - 3032:3032
    environment:
      - HTTP_PORT=3032
    networks:
      - myapp

  proto:
    image: morozhka/proto:v0.1.0
    container_name: proto
    build:
      context: proto-service
      dockerfile: Dockerfile
    ports:
      - 3033:3033
    environment:
      - HTTP_PORT=3033
    networks:
      - myapp